### PR TITLE
To make a disconnect 

### PR DESCRIPTION
**Pull request by toddAwesome**

### CODE REVIEW

**Comment by Asigi** [comment]
So what happened?

Sent from Yahoo Mail on Android

**Comment by Asigi** [comment]
I'm going to eat and bathe.

Skype around 11:15

Sent from Yahoo Mail on Android

**Comment by toddAwesome** [comment]
kk

**Comment by Asigi** [comment]
Actually, I need more time to eat.

See you in 10 minutes

Sent from Yahoo Mail on Android

**Comment by toddAwesome** [comment]
hey im at school in the tv room of the library

**Comment by toddAwesome** [comment]
hey here is mine submit it with your review and don't forget to do it
have a great break

**Pull request closed without merging**
